services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

volumes:
  postgres_data: