# Generated by Django 5.2.1 on 2025-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_de',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='types',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='types',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='types',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='types',
            name='name_de',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='types',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='types',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
    ]
