# Generated by Django 5.2.1 on 2025-09-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_categories_name_de_categories_name_en_and_more'),
    ]

    operations = [
    ]
