# Generated by Django 5.2.1 on 2025-09-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_init_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['order'], 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='categories',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
