# Generated by Django 5.2.1 on 2025-10-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_categories_options_categories_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='image',
        ),
        migrations.AddField(
            model_name='types',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
    ]
